project_id = "pbtgvcjniayedqlajjzz"

[functions.normalize-storage-files]
verify_jwt = false

[functions.storage-access]
verify_jwt = false

[functions.registration-chat]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.sales-chat]
verify_jwt = false